import type { Html2FigmaConfig } from "../src/types.js";

export default {
  input: "/Users/acool.ffei/Desktop/gjzq_internship/system_product _prototype/活动管理demo/index.html",
  viewport: { width: 1440, height: 900 },
  states: [
    { id: "channel-flow", url: "/", waitFor: 200 },
    { id: "request-menu", from: "channel-flow", click: ".request", waitFor: 200 },
    { id: "maintenance-modal", from: "request-menu", click: ".open-maintenance-modal", waitFor: 250 },
    { id: "maintenance-add-menu", from: "maintenance-modal", click: ".channel-add", waitFor: 200 },
    { id: "ip-build-modal", from: "maintenance-add-menu", click: ".ip-build-add", waitFor: 250 },
    { id: "restore-modal", from: "maintenance-add-menu", click: ".restore-cancel", waitFor: 250 },
    { id: "maintenance-change-menu", from: "maintenance-modal", click: ".channel-change", waitFor: 200 },
    { id: "other-info-modal", from: "maintenance-change-menu", click: ".other-info-change", waitFor: 250 },
    { id: "cancel-modal", from: "maintenance-modal", click: ".channel-cancel", waitFor: 250 },
    { id: "new-channel", from: "channel-flow", click: '[data-page="new-channel"]', waitFor: 250 },
    { id: "activity-management", from: "channel-flow", click: '[data-page="activity-management"]', waitFor: 250 },
    { id: "activity-form-modal", from: "activity-management", click: "#activity-add", waitFor: 250 },
    { id: "activity-import-modal", from: "activity-management", click: "#activity-import", waitFor: 250 },
    { id: "activity-history-modal", from: "activity-management", click: "#activity-history", waitFor: 250 },
  ],
  discovery: {
    include: ["button", "a", "[role=button]", "[data-figma-capture]"],
    exclude: [
      "[data-no-capture]",
      "a[target=_blank]",
      ".modal-close",
      ".sub-modal-close",
      ".cancel-close",
      ".activity-form-close",
      ".activity-import-close",
      ".activity-history-close",
      ".fullscreen",
      ".logout",
    ],
    maxDepth: 100,
    maxAutoStates: 1000,
    maxCandidatesPerState: 200,
    maxModalActionsPerPath: 2,
    maxPageActionsPerPath: 2,
    inventoryExtraStates: 3,
    maxEmptyExpansions: 12,
    skipTextPatterns: [
      "^查询$",
      "^重置$",
      "^刷新$",
      "^导出$",
      "^保存$",
      "^取消$",
      "^下载",
      "下载$",
      "^开始导入$",
      "^失败原因下载$",
      "^[‹›<>]$",
      "^\\d+$",
    ],
  },
  output: {
    mode: "new-version-page",
    pageName: "国金证券活动管理 {{timestamp}}",
  },
} satisfies Html2FigmaConfig;
